<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace>ImeCaretIndicator</RootNamespace>
    <AssemblyName>ImeCaretIndicator</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ImeCaretIndicator.Core\ImeCaretIndicator.Core.csproj" />
  </ItemGroup>

</Project>
